In [13]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

print(f"PyTorch version: {torch.__version__}")
print(f"CUDA available: {torch.cuda.is_available()}")

PyTorch version: 2.14.0+cu130
CUDA available: True


**Bài 1. Tạo Tensor cơ bản**

**Yêu cầu**: Cho biết kích thước, số chiều và kiểu dữ liệu của Tensor a.

In [14]:
import torch

a = torch.tensor(
    [[6, 7, 9],
     [69, 96, 99]],
    dtype=torch.int32
)
print("Tensor a: ", a)

# Yêu cầu: Cho biết kích thước, số chiều và kiểu dữ liệu của Tensor a
print("--- Thông tin của Tensor a ---")
print("Kích thước (Shape/Size):", a.shape)
print("Số chiều (ndim):", a.ndim)
print("Kiểu dữ liệu (dtype):", a.dtype)

Tensor a:  tensor([[ 6,  7,  9],
        [69, 96, 99]], dtype=torch.int32)
--- Thông tin của Tensor a ---
Kích thước (Shape/Size): torch.Size([2, 3])
Số chiều (ndim): 2
Kiểu dữ liệu (dtype): torch.int32


**Bài 2. Tạo các Tensor thường dùng**

**Yêu cầu:**

• Nhận xét sự khác nhau giữa torch.rand() và torch.randn().

• Tạo thêm một Tensor 5 × 5 chứa toàn giá trị 10.

In [15]:
import torch

# 1. Nhận xét sự khác nhau giữa torch.rand() và torch.randn()
print("=== 1. Phân biệt torch.rand() và torch.randn() ===")
print("- torch.rand(): Sinh các số ngẫu nhiên theo phân phối đều (Uniform distribution) trong khoảng [0, 1).")
print("- torch.randn(): Sinh các số ngẫu nhiên theo phân phối chuẩn (Standard Normal distribution) với trung bình mean=0 và độ lệch chuẩn std=1.")

a = torch.rand(3, 4)
b = torch.randn(3, 4)
c = torch.zeros(2, 3)
d = torch.ones(2, 3)
e = torch.eye(4)

print("torch.rand(3, 4):", a)
print("torch.randn(3, 4):", b)
print("torch.zeros(2, 3):", c)
print("torch.ones(2, 3):", d)
print("torch.eye(4):", e)

# 2. Tạo thêm một Tensor 5 x 5 chứa toàn giá trị 10
print("=== 2. Tensor 5 x 5 chứa toàn giá trị 10 ===")
tensor_10 = torch.full((5, 5), 10)
print(tensor_10)

=== 1. Phân biệt torch.rand() và torch.randn() ===
- torch.rand(): Sinh các số ngẫu nhiên theo phân phối đều (Uniform distribution) trong khoảng [0, 1).
- torch.randn(): Sinh các số ngẫu nhiên theo phân phối chuẩn (Standard Normal distribution) với trung bình mean=0 và độ lệch chuẩn std=1.
torch.rand(3, 4): tensor([[0.5970, 0.9205, 0.7307, 0.1555],
        [0.2374, 0.8205, 0.1775, 0.0995],
        [0.3773, 0.9148, 0.5741, 0.5306]])
torch.randn(3, 4): tensor([[ 0.7609,  0.9309,  1.8560, -0.0427],
        [-0.0135,  0.2783, -1.2158,  0.3426],
        [-0.8261,  0.7212, -1.6875,  0.6679]])
torch.zeros(2, 3): tensor([[0., 0., 0.],
        [0., 0., 0.]])
torch.ones(2, 3): tensor([[1., 1., 1.],
        [1., 1., 1.]])
torch.eye(4): tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])
=== 2. Tensor 5 x 5 chứa toàn giá trị 10 ===
tensor([[10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 

**Bài 3. Kiểm tra thông tin Tensor**

**Yêu cầu:** Giải thích ý nghĩa của torch.Size([2, 3, 4]).

In [16]:
import torch

a = torch.zeros(2, 3, 4)
print("Tensor:")
print(a)
print("Shape:", a.shape)
print("Size:", a.size())
print("Number of dimensions:", a.ndim)
print("Data type:", a.dtype)

# Yêu cầu: Giải thích ý nghĩa của torch.Size([2, 3, 4])
print("--- Giải thích torch.Size([2, 3, 4]) ---")
print("torch.Size([2, 3, 4]) nghĩa là Tensor có 3 chiều (3D Tensor):")
print("- Chiều 1 (dim 0): chứa 2 khối / ma trận 2D.")
print("- Chiều 2 (dim 1): mỗi khối chứa 3 hàng.")
print("- Chiều 3 (dim 2): mỗi hàng chứa 4 cột.")
print("- Tổng số phần tử trong Tensor: 2 * 3 * 4 = 24 phần tử.")

Tensor:
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
Shape: torch.Size([2, 3, 4])
Size: torch.Size([2, 3, 4])
Number of dimensions: 3
Data type: torch.float32
--- Giải thích torch.Size([2, 3, 4]) ---
torch.Size([2, 3, 4]) nghĩa là Tensor có 3 chiều (3D Tensor):
- Chiều 1 (dim 0): chứa 2 khối / ma trận 2D.
- Chiều 2 (dim 1): mỗi khối chứa 3 hàng.
- Chiều 3 (dim 2): mỗi hàng chứa 4 cột.
- Tổng số phần tử trong Tensor: 2 * 3 * 4 = 24 phần tử.


**Bài 4. Slicing và Indexing**

**Yêu cầu:**

• Cho biết shape của a[1] và a[1:, 2:4].

• Thử lấy hai phần tử cuối cùng trên chiều thứ ba.

In [17]:
import torch

a = torch.randn(3, 4, 5)
print("Original tensor shape:", a.shape)

# Yêu cầu 1: Cho biết shape của a[1] và a[1:, 2:4]
print("=== 1. Shape của các phần tử slicing ===")
print("a[1] shape:", a[1].shape)
print("a[1:, 2:4] shape:", a[1:, 2:4].shape)

# Yêu cầu 2: Thử lấy hai phần tử cuối cùng trên chiều thứ ba
print("=== 2. Hai phần tử cuối cùng trên chiều thứ ba (dim 2) ===")
last_two_dim3 = a[:, :, -2:]
print("Cú pháp: a[:, :, -2:]")
print("Shape kết quả:", last_two_dim3.shape)
print("Giá trị:", last_two_dim3)

Original tensor shape: torch.Size([3, 4, 5])
=== 1. Shape của các phần tử slicing ===
a[1] shape: torch.Size([4, 5])
a[1:, 2:4] shape: torch.Size([2, 2, 5])
=== 2. Hai phần tử cuối cùng trên chiều thứ ba (dim 2) ===
Cú pháp: a[:, :, -2:]
Shape kết quả: torch.Size([3, 4, 2])
Giá trị: tensor([[[ 0.2835,  1.3084],
         [ 0.8715,  0.4974],
         [-0.2180, -0.7283],
         [-0.7587,  0.4981]],

        [[ 1.7655, -1.5609],
         [-2.0661,  0.8267],
         [ 0.5618, -0.6510],
         [-0.7887, -0.1793]],

        [[ 0.1792, -0.0836],
         [ 1.2486,  0.3753],
         [-0.0273,  0.6610],
         [ 0.3394, -1.4363]]])


**Bài 5. Reshape và Flatten**

**Yêu cầu:**

• Kiểm tra số phần tử trước và sau khi reshape.

• Thử reshape Tensor thành kích thước 2 × 6.

In [18]:
import torch

a = torch.randn(3, 4)
print("Original tensor shape:", a.shape)
print("Original tensor:", a)

# Yêu cầu 1: Kiểm tra số phần tử trước và sau khi reshape
print("=== 1. Kiểm tra số phần tử trước và sau khi reshape ===")
num_elements_before = a.numel()
a_flatten = a.ravel()
a_reshaped = a.reshape(3, 2, 2)
print("Số phần tử trước khi reshape (a.numel()):", num_elements_before)
print("Số phần tử sau khi flatten (a_flatten.numel()):", a_flatten.numel())
print("Số phần tử sau khi reshape 3x2x2 (a_reshaped.numel()):", a_reshaped.numel())
print("-> Nhận xét: Tổng số phần tử giữ nguyên không đổi (3 * 4 = 12 phần tử).")

# Yêu cầu 2: Thử reshape Tensor thành kích thước 2 x 6
print("=== 2. Reshape Tensor thành kích thước 2 x 6 ===")
a_2x6 = a.reshape(2, 6)
print("Shape:", a_2x6.shape)
print("Giá trị:", a_2x6)

Original tensor shape: torch.Size([3, 4])
Original tensor: tensor([[ 0.4230,  1.1918, -0.1297,  0.1163],
        [ 0.6447, -0.7474,  0.7266, -0.3750],
        [ 0.7920,  0.2332, -0.8139, -0.3814]])
=== 1. Kiểm tra số phần tử trước và sau khi reshape ===
Số phần tử trước khi reshape (a.numel()): 12
Số phần tử sau khi flatten (a_flatten.numel()): 12
Số phần tử sau khi reshape 3x2x2 (a_reshaped.numel()): 12
-> Nhận xét: Tổng số phần tử giữ nguyên không đổi (3 * 4 = 12 phần tử).
=== 2. Reshape Tensor thành kích thước 2 x 6 ===
Shape: torch.Size([2, 6])
Giá trị: tensor([[ 0.4230,  1.1918, -0.1297,  0.1163,  0.6447, -0.7474],
        [ 0.7266, -0.3750,  0.7920,  0.2332, -0.8139, -0.3814]])


**Bài 6. Phép toán và nhân ma trận**

**Yêu cầu:**

• Phân biệt phép toán a * b với a @ b.T.

• Cho biết shape của kết quả a @ b.T.

In [19]:
import torch

a = torch.randn(2, 3)
b = torch.randn(2, 3)

print("a:", a)
print("b:", b)

# Yêu cầu 1: Phân biệt phép toán a * b với a @ b.T
print("=== 1. Phân biệt a * b và a @ b.T ===")
print("- a * b: Phép nhân từng phần tử tương ứng (Element-wise / Hadamard product). Yêu cầu a và b phải cùng shape.")
print("  Kết quả a * b:", a * b)

print("- a @ b.T: Phép nhân ma trận (Matrix multiplication / Dot product) giữa ma trận a (2x3) và chuyển vị b.T (3x2).")
print("  Kết quả a @ b.T:", a @ b.T)

# Yêu cầu 2: Cho biết shape của kết quả a @ b.T
print("=== 2. Shape của kết quả a @ b.T ===")
print("Shape của a @ b.T:", (a @ b.T).shape)

a: tensor([[-0.4378,  0.9475,  0.3333],
        [-1.0147, -1.0106, -1.7588]])
b: tensor([[ 0.6276,  1.4425, -1.1764],
        [-2.1177,  0.6245, -0.4307]])
=== 1. Phân biệt a * b và a @ b.T ===
- a * b: Phép nhân từng phần tử tương ứng (Element-wise / Hadamard product). Yêu cầu a và b phải cùng shape.
  Kết quả a * b: tensor([[-0.2748,  1.3668, -0.3921],
        [ 2.1489, -0.6311,  0.7576]])
- a @ b.T: Phép nhân ma trận (Matrix multiplication / Dot product) giữa ma trận a (2x3) và chuyển vị b.T (3x2).
  Kết quả a @ b.T: tensor([[ 0.6999,  1.3753],
        [-0.0254,  2.2754]])
=== 2. Shape của kết quả a @ b.T ===
Shape của a @ b.T: torch.Size([2, 2])


**Bài 7. Các hàm thống kê trên Tensor**

**Yêu cầu:**

• Thay dim=0 bằng dim=1 và nhận xét sự khác nhau.

In [20]:
import torch

a = torch.randn(3, 4)
print("Tensor a (3x4):", a)

print("=== Thống kê với dim=0 (tính theo chiều cột / dọc) ===")
print("Mean (dim=0):", torch.mean(a, dim=0))
print("Std (dim=0):", torch.std(a, dim=0))
print("Cumsum (dim=0):", torch.cumsum(a, dim=0))

# Yêu cầu: Thay dim=0 bằng dim=1 và nhận xét sự khác nhau
print("=== Yêu cầu: Thống kê với dim=1 (tính theo chiều hàng / ngang) ===")
print("Mean (dim=1):", torch.mean(a, dim=1))
print("Std (dim=1):", torch.std(a, dim=1))
print("Cumsum (dim=1):", torch.cumsum(a, dim=1))

print("--- Nhận xét sự khác nhau ---")
print("- Với dim=0: Phép toán thu gọn các hàng lại, kết quả trả về cho từng cột (kích thước output có 4 phần tử).")
print("- Với dim=1: Phép toán thu gọn các cột lại, kết quả trả về cho từng hàng (kích thước output có 3 phần tử).")

Tensor a (3x4): tensor([[-0.3166,  0.6613, -0.1261, -0.5556],
        [ 0.5568,  0.0114,  0.2495, -0.5975],
        [-1.0366, -0.1470,  0.5345,  0.3627]])
=== Thống kê với dim=0 (tính theo chiều cột / dọc) ===
Mean (dim=0): tensor([-0.2655,  0.1752,  0.2193, -0.2635])
Std (dim=0): tensor([0.7979, 0.4284, 0.3313, 0.5427])
Cumsum (dim=0): tensor([[-0.3166,  0.6613, -0.1261, -0.5556],
        [ 0.2401,  0.6727,  0.1234, -1.1531],
        [-0.7965,  0.5257,  0.6579, -0.7904]])
=== Yêu cầu: Thống kê với dim=1 (tính theo chiều hàng / ngang) ===
Mean (dim=1): tensor([-0.0843,  0.0550, -0.0716])
Std (dim=1): tensor([0.5272, 0.4890, 0.7054])
Cumsum (dim=1): tensor([[-0.3166,  0.3447,  0.2186, -0.3370],
        [ 0.5568,  0.5682,  0.8177,  0.2202],
        [-1.0366, -1.1837, -0.6492, -0.2865]])
--- Nhận xét sự khác nhau ---
- Với dim=0: Phép toán thu gọn các hàng lại, kết quả trả về cho từng cột (kích thước output có 4 phần tử).
- Với dim=1: Phép toán thu gọn các cột lại, kết quả trả về cho từng

**Bài 8. Autograd cơ bản**

**Yêu cầu:**

• Tính thủ công đạo hàm của y = x2 tại x = 3.6 và so sánh với x.grad.

• Đổi hàm thành y = 3*x**2 + 2*x + 1 và kiểm tra gradient.

In [21]:
import torch

# 1. Tính thủ công đạo hàm của y = x^2 tại x = 3.6 và so sánh với x.grad
print("=== 1. Hàm y = x^2 tại x = 3.6 ===")
x1 = torch.tensor(3.6, requires_grad=True)
y1 = x1 * x1
y1.backward()

grad_autograd_1 = x1.grad.item()
grad_manual_1 = 2 * 3.6

print(f"y1 = {y1.item()}")
print(f"x1.grad (Autograd): {grad_autograd_1}")
print(f"Đạo hàm thủ công (2 * 3.6): {grad_manual_1}")
print(f"Khớp nhau: {abs(grad_autograd_1 - grad_manual_1) < 1e-5}")

# 2. Đổi hàm thành y = 3*x**2 + 2*x + 1 và kiểm tra gradient
print("=== 2. Đổi hàm thành y = 3*x^2 + 2*x + 1 tại x = 3.6 ===")
x2 = torch.tensor(3.6, requires_grad=True)
y2 = 3 * (x2**2) + 2 * x2 + 1
y2.backward()

grad_autograd_2 = x2.grad.item()
grad_manual_2 = 6 * 3.6 + 2.0

print(f"y2 = {y2.item()}")
print(f"x2.grad (Autograd): {grad_autograd_2}")
print(f"Đạo hàm thủ công (6 * 3.6 + 2): {grad_manual_2}")
print(f"Khớp nhau: {abs(grad_autograd_2 - grad_manual_2) < 1e-5}")

=== 1. Hàm y = x^2 tại x = 3.6 ===
y1 = 12.959999084472656
x1.grad (Autograd): 7.199999809265137
Đạo hàm thủ công (2 * 3.6): 7.2
Khớp nhau: True
=== 2. Đổi hàm thành y = 3*x^2 + 2*x + 1 tại x = 3.6 ===
y2 = 47.07999801635742
x2.grad (Autograd): 23.599998474121094
Đạo hàm thủ công (6 * 3.6 + 2): 23.6
Khớp nhau: True


**Bài 9. Gradient Descent tìm hệ số đa thức**

**Yêu cầu:**

• So sánh ba hệ số học được với [1, 2, 3].

• Giải thích vai trò của optimizer.zero_grad(), mse.backward() và optimizer.step().

In [22]:
import numpy as np
import torch

polynomial = np.poly1d([1, 2, 3])
N = 20
X = np.random.randn(N, 1) * 5
Y = polynomial(X)
XX = np.hstack([X * X, X, np.ones_like(X)])

w = torch.randn(3, 1, requires_grad=True)
x = torch.tensor(XX, dtype=torch.float32)
y = torch.tensor(Y, dtype=torch.float32)

optimizer = torch.optim.NAdam([w], lr=0.01)
print("Initial coefficients:", w.detach().numpy().flatten())

for epoch in range(1000):
    optimizer.zero_grad()
    y_pred = x @ w
    mse = torch.mean(torch.square(y - y_pred))
    mse.backward()
    optimizer.step()

learned_coeffs = w.detach().numpy().flatten()
print("Learned coefficients:", learned_coeffs)

# 1. So sánh ba hệ số học được với [1, 2, 3]
print("=== 1. So sánh hệ số học được với [1, 2, 3] ===")
print("Hệ số thực tế target: [1.0, 2.0, 3.0]")
print("Hệ số học được:     ", learned_coeffs)
print("Độ chênh lệch absolute error:", np.abs(learned_coeffs - np.array([1, 2, 3])))

# 2. Giải thích vai trò của optimizer.zero_grad(), mse.backward() và optimizer.step()
print("=== 2. Giải thích vai trò của các hàm ===")
print("- optimizer.zero_grad(): Đặt gradient của các tham số (w) về 0 trước bước tính mới, tránh cộng dồn gradient từ epoch trước.")
print("- mse.backward(): Thực hiện lan truyền ngược (backpropagation) tính đạo hàm của loss theo w và lưu vào w.grad.")
print("- optimizer.step(): Cập nhật trọng số w theo gradient vừa tính và thuật toán NAdam.")

Initial coefficients: [-0.29024297 -0.06562939  0.08790365]
Learned coefficients: [1.0168535 1.9869567 2.0248473]
=== 1. So sánh hệ số học được với [1, 2, 3] ===
Hệ số thực tế target: [1.0, 2.0, 3.0]
Hệ số học được:      [1.0168535 1.9869567 2.0248473]
Độ chênh lệch absolute error: [0.01685345 0.01304328 0.97515273]
=== 2. Giải thích vai trò của các hàm ===
- optimizer.zero_grad(): Đặt gradient của các tham số (w) về 0 trước bước tính mới, tránh cộng dồn gradient từ epoch trước.
- mse.backward(): Thực hiện lan truyền ngược (backpropagation) tính đạo hàm của loss theo w và lưu vào w.grad.
- optimizer.step(): Cập nhật trọng số w theo gradient vừa tính và thuật toán NAdam.


**Bài 10. Giải hệ phương trình bằng Autograd**

**Yêu cầu:**

• Kiểm tra nghiệm thu được với bốn phương trình: A+B=9, C-D=1, A+C=8, B-D=2.

• Nhận xét vì sao bài toán có thể có nhiều nghiệm.

In [23]:
import random
import torch

A = torch.tensor(random.random(), requires_grad=True)
B = torch.tensor(random.random(), requires_grad=True)
C = torch.tensor(random.random(), requires_grad=True)
D = torch.tensor(random.random(), requires_grad=True)

EPOCHS = 2000
optimizer = torch.optim.NAdam([A, B, C, D], lr=0.01)

for _ in range(EPOCHS):
    y1 = A + B - 9
    y2 = C - D - 1
    y3 = A + C - 8
    y4 = B - D - 2
    sqerr = y1*y1 + y2*y2 + y3*y3 + y4*y4
    optimizer.zero_grad()
    sqerr.backward()
    optimizer.step()

print("Nghiệm tìm được:")
print("A =", A.item())
print("B =", B.item())
print("C =", C.item())
print("D =", D.item())

# 1. Kiểm tra nghiệm thu được với bốn phương trình
print("=== 1. Kiểm tra nghiệm thu được ===")
eq1 = A.item() + B.item()
eq2 = C.item() - D.item()
eq3 = A.item() + C.item()
eq4 = B.item() - D.item()

print(f"PT 1: A + B = {eq1:.4f} (Target: 9)")
print(f"PT 2: C - D = {eq2:.4f} (Target: 1)")
print(f"PT 3: A + C = {eq3:.4f} (Target: 8)")
print(f"PT 4: B - D = {eq4:.4f} (Target: 2)")
print(f"Tổng sai số bình phương (Loss): {sqerr.item():.6f}")

# 2. Nhận xét vì sao bài toán có thể có nhiều nghiệm
print("=== 2. Nhận xét vì sao bài toán có nhiều nghiệm (vô số nghiệm) ===")
print("- Hệ phương trình có 4 ẩn (A, B, C, D) nhưng các phương trình bị phụ thuộc tuyến tính:")
print("  (A + B = 9) và (A + C = 8) => B - C = 1.")
print("  Kết hợp (C - D = 1) => B - D = 2 (trùng với PT 4).")
print("- Ma trận hệ số có rank = 3 < 4 (số ẩn), do đó hệ có vô số nghiệm. Thuật toán Gradient Descent sẽ hội tụ về nghiệm tùy thuộc vào điểm khởi tạo ban đầu của các biến.")

Nghiệm tìm được:
A = 4.618962287902832
B = 4.380981922149658
C = 3.3810038566589355
D = 2.380990505218506
=== 1. Kiểm tra nghiệm thu được ===
PT 1: A + B = 8.9999 (Target: 9)
PT 2: C - D = 1.0000 (Target: 1)
PT 3: A + C = 8.0000 (Target: 8)
PT 4: B - D = 2.0000 (Target: 2)
Tổng sai số bình phương (Loss): 0.000000
=== 2. Nhận xét vì sao bài toán có nhiều nghiệm (vô số nghiệm) ===
- Hệ phương trình có 4 ẩn (A, B, C, D) nhưng các phương trình bị phụ thuộc tuyến tính:
  (A + B = 9) và (A + C = 8) => B - C = 1.
  Kết hợp (C - D = 1) => B - D = 2 (trùng với PT 4).
- Ma trận hệ số có rank = 3 < 4 (số ẩn), do đó hệ có vô số nghiệm. Thuật toán Gradient Descent sẽ hội tụ về nghiệm tùy thuộc vào điểm khởi tạo ban đầu của các biến.


**Bài 11. Viết chương trình PyTorch để thực hiện các yêu cầu sau:**

• Tạo Tensor X có 24 phần tử và reshape lần lượt thành 4 × 6, 2 × 12 và 2 × 3 × 4.

• Tạo hai Tensor A, B kích thước 3 × 4; tính A+B, A*B, A/B, trung bình theo cột và độ lệch chuẩn theo cột.

• Cho y = 2x2 + 5x + 3. Dùng autograd tính dy/dx tại x = 2 và kiểm tra bằng phép tính thủ công.

• Thay đa thức trong Bài 9 bằng y = 2x2 - 3x + 5; huấn luyện và cho biết các hệ số tìm được.


In [12]:
import torch
import numpy as np

# -------------------------------------------------------------------------
# 1. Tạo Tensor X có 24 phần tử và reshape lần lượt
# -------------------------------------------------------------------------
print("=== Yêu cầu 1: Reshape Tensor X ===")
X = torch.arange(1, 25, dtype=torch.float32)
print("Tensor X ban đầu (24 phần tử):", X)

X_4x6 = X.reshape(4, 6)
print("\nReshape thành 4x6:\n", X_4x6)

X_2x12 = X.reshape(2, 12)
print("\nReshape thành 2x12:\n", X_2x12)

X_2x3x4 = X.reshape(2, 3, 4)
print("\nReshape thành 2x3x4:\n", X_2x3x4)


# -------------------------------------------------------------------------
# 2. Phép toán trên hai Tensor A, B (kích thước 3x4)
# -------------------------------------------------------------------------
print("\n=== Yêu cầu 2: Phép toán trên Tensor A, B ===")
A = torch.randn(3, 4)
B = torch.randn(3, 4)
print("Tensor A:\n", A)
print("Tensor B:\n", B)

print("\nA + B:\n", A + B)
print("A * B (Hadamard product):\n", A * B)
print("A / B (Element-wise division):\n", A / B)

# Trung bình và độ lệch chuẩn theo cột (dim=0)
print("\nTrung bình theo cột của A:\n", torch.mean(A, dim=0))
print("Độ lệch chuẩn theo cột của A:\n", torch.std(A, dim=0))
print("Trung bình theo cột của B:\n", torch.mean(B, dim=0))
print("Độ lệch chuẩn theo cột của B:\n", torch.std(B, dim=0))


# -------------------------------------------------------------------------
# 3. Tính dy/dx của y = 2x^2 + 5x + 3 tại x = 2 với autograd & kiểm tra thủ công
# -------------------------------------------------------------------------
print("\n=== Yêu cầu 3: Autograd tính đạo hàm ===")
x = torch.tensor(2.0, requires_grad=True)
y = 2 * (x**2) + 5 * x + 3
y.backward()

grad_autograd = x.grad.item()
# Đạo hàm thủ công: dy/dx = 4x + 5. Tại x = 2: 4*(2) + 5 = 13.0
grad_manual = 4 * 2.0 + 5.0

print(f"Giá trị y tại x = 2: {y.item()}")
print(f"Đạo hàm dy/dx tính bởi Autograd: {grad_autograd}")
print(f"Đạo hàm dy/dx tính thủ công: {grad_manual}")
print(f"Kết quả trùng khớp: {np.isclose(grad_autograd, grad_manual)}")


# -------------------------------------------------------------------------
# 4. Huấn luyện Gradient Descent tìm hệ số đa thức y = 2x^2 - 3x + 5
# -------------------------------------------------------------------------
print("\n=== Yêu cầu 4: Gradient Descent tìm hệ số y = 2x^2 - 3x + 5 ===")
# Tạo dữ liệu giả định theo đa thức y = 2x^2 - 3x + 5
polynomial_target = np.poly1d([2, -3, 5])
N = 100
X_np = np.random.randn(N, 1) * 5
Y_np = polynomial_target(X_np)

# Xây dựng ma trận đặc trưng [x^2, x, 1]
XX_np = np.hstack([X_np**2, X_np, np.ones_like(X_np)])

x_tensor = torch.tensor(XX_np, dtype=torch.float32)
y_tensor = torch.tensor(Y_np, dtype=torch.float32)

# Khởi tạo tham số w ngẫu nhiên
w = torch.randn(3, 1, requires_grad=True)
optimizer = torch.optim.NAdam([w], lr=0.01)

print("Hệ số khởi tạo ban đầu:\n", w.detach().numpy().flatten())

# Vòng lặp huấn luyện
EPOCHS = 2000
for epoch in range(EPOCHS):
    optimizer.zero_grad()
    y_pred = x_tensor @ w
    mse = torch.mean((y_tensor - y_pred) ** 2)
    mse.backward()
    optimizer.step()

learned_coeffs = w.detach().numpy().flatten()
print(f"\nHệ số học được sau {EPOCHS} epochs: {learned_coeffs}")
print("Hệ số thực tế target [2, -3, 5]: [2.0, -3.0, 5.0]")


=== Yêu cầu 1: Reshape Tensor X ===
Tensor X ban đầu (24 phần tử): tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
        15., 16., 17., 18., 19., 20., 21., 22., 23., 24.])

Reshape thành 4x6:
 tensor([[ 1.,  2.,  3.,  4.,  5.,  6.],
        [ 7.,  8.,  9., 10., 11., 12.],
        [13., 14., 15., 16., 17., 18.],
        [19., 20., 21., 22., 23., 24.]])

Reshape thành 2x12:
 tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
        [13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24.]])

Reshape thành 2x3x4:
 tensor([[[ 1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.],
         [ 9., 10., 11., 12.]],

        [[13., 14., 15., 16.],
         [17., 18., 19., 20.],
         [21., 22., 23., 24.]]])

=== Yêu cầu 2: Phép toán trên Tensor A, B ===
Tensor A:
 tensor([[ 1.3576,  0.6690,  0.9048, -0.3222],
        [ 2.1151, -0.9128,  0.6213, -1.0260],
        [ 1.5078,  1.7714,  0.1384, -0.3823]])
Tensor B:
 tensor([[ 1.4698, -1.3164, -0.